baseURL = 'https://itexperts.team/'
languageCode = 'ru'
title = 'IT Experts Team'
theme = 'mainroad'

[services.disqus]
    shortname = "Stas"

#[module.imports]
#    path = "github.com/imfing/hextra"

[Params]
    opengraph = true
    schema = true
    readmore = true
    authorbox = false
    toc = true
    pager = true
    post_meta = ["author", "date", "categories"]
    mainSections = ["posts", "about", "contact"]
    dateformat = "2006-01-02"

[Params.Author] # Used in authorbox
  name = "Станислав Обидин"
  bio = ""
  avatar = "img/so_1.jpg" 

[Params.style.vars]
  highlightColor = "#2d5de2" # Override highlight color
  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/logo_team.png" # Logo image. Path relative to "static"
  title = "ЭКСПЕРТЫ ИТ" # Logo title, otherwise will use site title
  subtitle = "МЫ РОЖДАЕМ ИДЕИ, РАЗВИВАЕМ ПРОЕКТЫ И РЕШАЕМ ЗАДАЧИ" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  #linkedin = "username"
  telegram = "@sobidin"
  github = "smobidin"
  #email = "stas@itexperts.team"
  phone = "+7 (926) 530 46 87"

